name: accountbook
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  pdf: ^3.10.8
  printing: ^5.11.1 

  # Add these Firebase packages
  firebase_core: ^3.3.0
  cloud_firestore: ^5.1.0
  firebase_auth: ^5.1.2
  
  http: ^1.2.1
  
  # ADD THIS LINE
  dotted_border: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true